Repository opentelekomcloud/provider-opentelekomcloud, pull requests merged in 2024-08, with the labels that each got.

#10 Rds selectors
  apis/rds/v1alpha1/zz_backupv3_types.go
  apis/rds/v1alpha1/zz_generated.deepcopy.go
  apis/rds/v1alpha1/zz_generated.managed.go
  apis/rds/v1alpha1/zz_generated.managedlist.go
  apis/rds/v1alpha1/zz_generated.resolvers.go
  apis/rds/v1alpha1/zz_generated_terraformed.go
  apis/rds/v1alpha1/zz_instancev1_types.go
  apis/rds/v1alpha1/zz_instancev3_types.go
  apis/rds/v1alpha1/zz_parametergroupv3_types.go
  apis/rds/v1alpha1/zz_readreplicav3_types.go
  config/compute/config.go
  config/external_name.go
  config/rds/config.go
  examples-generated/rds/backupv3.yaml
  examples-generated/rds/instancev1.yaml
  examples-generated/rds/instancev3.yaml
  examples-generated/rds/readreplicav3.yaml
  examples/rds/instance.yaml
  internal/controller/rds/instancev1/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/rds.opentelekomcloud.crossplane.io_backupv3s.yaml
  package/crds/rds.opentelekomcloud.crossplane.io_instancev1s.yaml
  package/crds/rds.opentelekomcloud.crossplane.io_instancev3s.yaml
  package/crds/rds.opentelekomcloud.crossplane.io_readreplicav3s.yaml
Labels: enhancement, gate

#13 Update README.md
  README.md
  cmd/provider/main.go
Labels: documentation, gate

#15 feat: labels and selectors for dcs InstanceV2
  Makefile
  apis/cce/v1alpha1/zz_generated.deepcopy.go
  apis/cce/v1alpha1/zz_nodev3_types.go
  apis/dcs/v1alpha1/zz_generated.conversion_hubs.go
  apis/dcs/v1alpha1/zz_generated.deepcopy.go
  apis/dcs/v1alpha1/zz_generated.managed.go
  apis/dcs/v1alpha1/zz_generated.managedlist.go
  apis/dcs/v1alpha1/zz_generated.resolvers.go
  apis/dcs/v1alpha1/zz_instancev1_terraformed.go
  apis/dcs/v1alpha1/zz_instancev1_types.go
  apis/dcs/v1alpha1/zz_instancev2_types.go
  apis/dds/v1alpha1/zz_generated.deepcopy.go
  apis/dds/v1alpha1/zz_instancev3_types.go
  apis/identity/v1alpha1/zz_agencyv3_types.go
  apis/lb/v1alpha1/zz_loadbalancerv3_types.go
  apis/rds/v1alpha1/zz_generated.deepcopy.go
  apis/rds/v1alpha1/zz_instancev3_types.go
  apis/waf/v1alpha1/zz_dedicatedpolicyv1_types.go
  apis/waf/v1alpha1/zz_generated.deepcopy.go
  config/dcs/config.go
  config/external_name.go
  config/provider-metadata.yaml
  config/schema.json
  examples-generated/dcs/v1alpha1/instancev1.yaml
  examples-generated/dcs/v1alpha1/instancev2.yaml
  examples-generated/rds/v1alpha1/instancev3.yaml
  examples/dcs/instance.yaml
  internal/controller/dcs/instancev1/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/cce.opentelekomcloud.crossplane.io_nodev3s.yaml
  package/crds/dcs.opentelekomcloud.crossplane.io_instancev1s.yaml
  package/crds/dcs.opentelekomcloud.crossplane.io_instancev2s.yaml
  package/crds/dds.opentelekomcloud.crossplane.io_instancev3s.yaml
  package/crds/identity.opentelekomcloud.crossplane.io_agencyv3s.yaml
  package/crds/lb.opentelekomcloud.crossplane.io_loadbalancerv3s.yaml
  package/crds/rds.opentelekomcloud.crossplane.io_instancev3s.yaml
  package/crds/waf.opentelekomcloud.crossplane.io_dedicatedpolicyv1s.yaml
Labels: enhancement, gate

#16 feat: add dds instance and backup selectors
  Makefile
  apis/dds/v1alpha1/zz_backupv3_terraformed.go
  apis/dds/v1alpha1/zz_backupv3_types.go
  apis/dds/v1alpha1/zz_generated.conversion_hubs.go
  apis/dds/v1alpha1/zz_generated.deepcopy.go
  apis/dds/v1alpha1/zz_generated.managed.go
  apis/dds/v1alpha1/zz_generated.managedlist.go
  apis/dds/v1alpha1/zz_generated.resolvers.go
  apis/dds/v1alpha1/zz_instancev3_types.go
  config/dds/config.go
  config/external_name.go
  config/provider.go
  examples-generated/dds/v1alpha1/backupv3.yaml
  examples-generated/dds/v1alpha1/instancev3.yaml
  examples/dds/backup.yaml
  examples/dds/instance.yaml
  internal/controller/dds/backupv3/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/dds.opentelekomcloud.crossplane.io_backupv3s.yaml
  package/crds/dds.opentelekomcloud.crossplane.io_instancev3s.yaml
Labels: enhancement, gate

#17 feat: labels for dis resources
  apis/dis/v1alpha1/zz_checkpointv2_types.go
  apis/dis/v1alpha1/zz_dumptaskv2_types.go
  apis/dis/v1alpha1/zz_generated.deepcopy.go
  apis/dis/v1alpha1/zz_generated.resolvers.go
  config/common/common.go
  config/deh/config.go
  config/dis/config.go
  examples-generated/dis/v1alpha1/checkpointv2.yaml
  examples-generated/dis/v1alpha1/dumptaskv2.yaml
  examples/dis/checkpoint.yaml
  examples/dis/dump_task.yaml
  package/crds/dis.opentelekomcloud.crossplane.io_checkpointv2s.yaml
  package/crds/dis.opentelekomcloud.crossplane.io_dumptaskv2s.yaml
Labels: gate
